apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: nginx
  namespace: argocd
spec:
  goTemplate: true
  goTemplateOptions: ["missingkey=error"]
  generators:
  - list:
      elements:
      - cluster: prod
        server: https://172.18.0.4:6443
      - cluster: stg
        server: https://172.18.0.3:6443
  template:
    metadata:
      name: 'nginx-{{.cluster}}'
    spec:
      project: nginx-project
      source:
        repoURL: 'https://github.com/testing-org-egarciam/laura-app.git'
        targetRevision: HEAD
        path: apps/nginx
      destination:
        server: '{{.server}}'
        namespace: nginx-ns
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
        - CreateNamespace=true
