apiVersion: v1
kind: Secret
metadata:
  name: repo-bitnami-helm
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  url: https://charts.bitnami.com/bitnami
  name: bitnami
  insecure: "true"
