apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laura-app-prod
  namespace: argocd
spec:
  destination:
    namespace: default
    server: https://172.18.0.4:6443
  project: laura-project
  sources:
  - helm:
      valueFiles:
      - $values/values/laura-app/prod.yaml
    path: charts/laura-app
    repoURL: https://github.com/testing-org-egarciam/laura-app.git
    targetRevision: main
  - ref: values
    repoURL: https://github.com/testing-org-egarciam/gitops-config.git
    targetRevision: main
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
