apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: laura-app-appset
  namespace: argocd
spec:
  generators:
    - git:
        repoURL: https://github.com/testing-org-egarciam/gitops-config.git
        revision: feat/application-sets
        files:
          - path: "values/laura-app/clusters/*.yaml"
  template:
    metadata:
      name: 'laura-app-{{path.basename}}'
    spec:
      project: laura-project
      source:
        repoURL: https://github.com/testing-org-egarciam/nginx-app.git
        targetRevision: HEAD
        path: charts/laura-app
        helm:
          valueFiles:
            - 'https://raw.githubusercontent.com/testing-org-egarciam/gitops-config/feat/application-sets/{{path}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: default
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
