apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: laura-app-stg
  namespace: argocd
spec:
  project: laura-project
  source:
    repoURL: https://github.com/testing-org-egarciam/laura-app.git
    targetRevision: HEAD
    path: charts/laura-app
    helm:
      valueFiles:
      - https://raw.githubusercontent.com/testing-org-egarciam/gitops-config/main/values/laura-app/stg.yaml
  destination:
    server: https://kubernetes.default.svc # ArgoCD will resolve this to the stg secret
    namespace: default
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
