apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: laura-project
  namespace: argocd
spec:
  description: Project for laura-app
  destinations:
  - namespace: default
    server: https://172.18.0.4:6443
  - namespace: default
    server: https://172.18.0.3:6443
  - namespace: default
    server: https://kubernetes.default.svc
  sourceRepos:
  - https://github.com/testing-org-egarciam/laura-app.git
  - https://github.com/testing-org-egarciam/gitops-config.git
