apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: nginx-stg
  namespace: argocd
spec:
  project: laura-project
  source:
    repoURL: 'https://github.com/testing-org-egarciam/laura-app.git'
    targetRevision: HEAD
    path: apps/nginx
  destination:
    server: https://172.18.0.3:6443
    namespace: nginx-ns
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
    - CreateNamespace=true
